### PR TITLE
adaptive trigger functionality & updated pico example

### PR DESCRIPTION
**Pull request by selimrecep**
Follow up merge request after https://github.com/ricardoquesada/bluepad32/pull/74 , solves https://github.com/ricardoquesada/bluepad32/issues/73
- Fixed the typo
- Cherrypicked my changes on develop branch

### CODE REVIEW

**Comment by selimrecep** [comment]
There is also other adaptive trigger effects I decided to not put as they are not marked "safe/official" by the source packet structure link I used as mentioned in the code, but other type of effects is also possible to add, for now the ones I added seemed enough for me.
I kinda didn't like the place I put the effect generator functions and couldn't think better way of implementing it in a more structured way, still welcome to opinions or changes.

**Comment by selimrecep** [comment]
Also another potential option is adding prepared trigger effects as it is hard to know which numbers to put in those functions for users (myself stumbled a bit to decide what's best to put by trial and error and I still don't think vibration effect is good enough)

**Comment by ricardoquesada** [comment]
Looks good to me. thanks.

**Comment by ricardoquesada** [comment]
@selimrecep Could you please check the errors reported by the CI builder ?

**Comment by ricardoquesada** [comment]
> Also another potential option is adding prepared trigger effects

I like that option

**Comment by selimrecep** [comment]
Tbh idk what https://github.com/ricardoquesada/bluepad32/actions/runs/8037696324/job/21954311773#step:4:45 is about seems to be something wrong with apt repositories maybe? Also https://github.com/ricardoquesada/bluepad32/actions/runs/8037696331/job/21954311822#step:6:51 too

I fixed formatting issue for https://github.com/ricardoquesada/bluepad32/actions/runs/8037696327/job/21954312053#step:3:47

**Comment by selimrecep** [comment]
For the dependencies problem you can try bumping from cmake_3.22.1-1ubuntu1.22.04.1_amd64.deb to cmake_3.22.1-1ubuntu1.22.04.2_amd64.deb if anything

**Comment by ricardoquesada** [comment]
perhaps I need to run `apt update` before... let me try that

**Comment by selimrecep** [comment]
i merged the updated ci conf

**Comment by bysiber** [comment]
This code is smoother than butter... hopefully the CI agrees

**Comment by ricardoquesada** [comment]
FYI: I made some changes to the API

**Comment by selimrecep** [comment]
I checked them out, sorry for dirty "assert()"s as it was a bit rush implementation :) Also good idea to structurizing the effects, thanks for contribution

**Comment by radimsejk** [comment]
Hi,

I do not see the adaptive trigger settings in Arduino/ESP32 examples. Is this still only in the develop branch or is it already possible to set in main ? Thanks.

**Pull request merged**
