### PR TITLE
Update ds4 parser

### PR DESCRIPTION
**Pull request by Jaboop8**
Recreating PR against Dev. Contains PS4 Parser changes for Touchpad, Accelerometer and Gyro.

### CODE REVIEW

**Comment by ricardoquesada** [comment]
Thanks for the pull request.

I reviewed it and there are a few comments:

- would it be possible to squash it? e.g; instead of sending 3 different commits, to just send one.
  This can be done by doing a `git rebase -i` and squash the 3 commits in one.
  By squashing it, it would be easier for me to review

- also, don't include commented code. Just remove the code that is not used, but don't comment it.
- and whenever possible try to follow the not-defined coding convention of using `use_underscore_for_variables`
- and try to reuse the `ds4_input_report_t` and add the missing values there (probably this would be the most important thing to do...)

I was planning to have a "mouse" data structure... so if you could do the squashing plus expanding and populating the `ds4_input_report_t` and do the rest.

Thanks!

**Comment by ste2425** [comment]
It would be great if this PR could make it in, or at least a part of it.

Having access to the track pad button on a DS4 at least would be brilliant.

**Comment by Jaboop8** [comment]
@ste2425 Hoping to get back around to this project soon. I've been swamped with other projects lately. If you need it sooner though check out the changes to uni_hid_parser_ds4.c. They are pretty minimal changes to the parsing of the report to make sense of the touchpad data

**Comment by ricardoquesada** [comment]
gyro/accel for dualshock4 / dualsense support added in develop branch.

Closing this pull request.

**Pull request closed without merging**
